#include "errors_dec.h"
/*
 * Function called to raise an errors generated by
 * the compiler
 */
 ERROR_STRUCT errors[ERRORS_NUMBER] = {
     {ERR_CAR_INC,"Undefined caracter"},{ERR_FICH_VID,"error 'empty'"},{UNEXPECTED_TOKEN,"unexpected symbol"},{EXPECTED_TOKEN_IF,"if() expression cannot be executed."},
     {EXPECTED_TOKEN_ELSE,"unexpected 'else'"},{EXPECTED_TOKEN_FOR,"unexpected 'for'"},{EXPECTED_TOKEN_REPEAT,"unexpected 'repeat'"},
     {EXPECTED_TOKEN_WHILE,"unexpected 'while'"},{EXPECTED_TOKEN_FUNCTION,"unexpected 'function'"},{EXPECTED_TOKEN_IN,"unexpected 'in'"},
     {EXPECTED_TOKEN_NEXT,"unexpected 'next'"},{EXPECTED_TOKEN_BREAK,"unexpected 'break'"},{EXPECTED_TOKEN_TRUE,"unexpected 'true'"},
     {EXPECTED_TOKEN_FALSE,"unexpected 'false'"},{EXPECTED_TOKEN_NULL,"unexpected 'null'"},{EXPECTED_TOKEN_ADD,"unexpected '+'"},
     {EXPECTED_TOKEN_SUB,"unexpected '-'"},{EXPECTED_TOKEN_MULT,"unexpected '*'"},{EXPECTED_TOKEN_DIV,"unexpected '/'"},
     {EXPECTED_TOKEN_EXPONENT,"unexpected 'exp'"},{EXPECTED_TOKEN_MODULUS,"unexpected 'mod'"},{EXPECTED_TOKEN_INT_DIV,"unexpected 'whole division'"},
     {EXPECTED_TOKEN_INF,"unexpected '<'"},{EXPECTED_TOKEN_SUP,"unexpected '>'"},{EXPECTED_TOKEN_INFEG,"unexpected '<='"},
     {EXPECTED_TOKEN_SUPEG,"unexpected '>='"},{EXPECTED_TOKEN_EQUALTO,"unexpected '=='"},{EXPECTED_TOKEN_NOT_EQUAL,"unexpected '!='"},
     {EXPECTED_TOKEN_LOGICAL_NOT,"unexpected 'not'"},{EXPECTED_TOKEN_LOGICAL_AND,"unexpected '&&'"},
     {EXPECTED_TOKEN_LOGICAL_OR,"unexpected '||'"},{EXPECTED_TOKEN_ELEMENTWISE_LOGICAL_AND,"unexpected 'and'"},
     {EXPECTED_TOKEN_ELEMENTWISE_LOGICAL_OR,"unexpected 'ELEMENTWISE LOGICAL OR'"},{ERR_ASSIGN,"error in assignement"},{EXPECTED_TOKEN_LEFT_ASGN,"expected LEFT_ASGN_TOKEN"},
     {EXPECTED_TOKEN_PO,"unexpected 'PO'"},{EXPECTED_TOKEN_PF,"unexpected 'PF'"},
     {EXPECTED_TOKEN_AO,"unexpected 'AO'"},{EXPECTED_TOKEN_AF,"unexpected 'AF'"},{EXPECTED_TOKEN_PRINT,"unexpected 'print'"},
     {EXPECTED_TOKEN_READLINE,"unexpected 'readline'"},{EXPECTED_TOKEN_RETURN,"unexpected 'return'"},{EXPECTED_TOKEN_CHARACTER,"unexpected 'character'"},
     {EXPECTED_TOKEN_PV,"unexpected ';'"},{EXPECTED_TOKEN_COMPLEX,"unexpected 'complex'"},{EXPECTED_TOKEN_HEX,"unexpected 'hex'"},
     {EXPECTED_TOKEN_NUM,"unexpected 'number'"},{EXPECTED_TOKEN_ID,"unexpected 'identifier'"},{EXPECTED_TOKEN_ERREUR,"unexpected 'error'"},
     {EXPECTED_TOKEN_APOST,"unexpected 'post'"},{EXPECTED_TOKEN_GUIL,"unexpected '''"},{EXPECTED_TOKEN_TWO_POINT,"unexpected ':'"},
     {EXPECTED_TOKEN_VIR,"unexpected ','"},{EXPECTED_TOKEN_COND,"unexpected 'condition'"},{EXPECTED_TOKEN_AFF,"unexpected '?'"},
     {EXPECTED_TOKEN_EOF,"unexpected EOF "},
   };
int raise_error(ERRORS error) {
	printf("Error number %i: %s on line %i \n", error, errors[error].ERROR_ST, current_line);
	exit(0);
}
